/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stream = IDL.Variant({
  'arts' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const Course = IDL.Variant({
  'bba' : IDL.Null,
  'bca' : IDL.Null,
  'bsc' : IDL.Null,
  'other' : IDL.Null,
  'bcom' : IDL.Null,
  'diploma' : IDL.Null,
});
export const EntranceExam = IDL.Variant({
  'jee' : IDL.Null,
  'cuet' : IDL.Null,
  'neet' : IDL.Null,
  'none' : IDL.Null,
});
export const Lead = IDL.Record({
  'twelfthStream' : Stream,
  'interestedCourse' : Course,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'district' : IDL.Text,
  'needsDrccSupport' : IDL.Bool,
  'twelfthPercentage' : IDL.Nat,
  'entranceExam' : EntranceExam,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Stream,
        IDL.Nat,
        Course,
        IDL.Bool,
        EntranceExam,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stream = IDL.Variant({
    'arts' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const Course = IDL.Variant({
    'bba' : IDL.Null,
    'bca' : IDL.Null,
    'bsc' : IDL.Null,
    'other' : IDL.Null,
    'bcom' : IDL.Null,
    'diploma' : IDL.Null,
  });
  const EntranceExam = IDL.Variant({
    'jee' : IDL.Null,
    'cuet' : IDL.Null,
    'neet' : IDL.Null,
    'none' : IDL.Null,
  });
  const Lead = IDL.Record({
    'twelfthStream' : Stream,
    'interestedCourse' : Course,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'district' : IDL.Text,
    'needsDrccSupport' : IDL.Bool,
    'twelfthPercentage' : IDL.Nat,
    'entranceExam' : EntranceExam,
  });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Stream,
          IDL.Nat,
          Course,
          IDL.Bool,
          EntranceExam,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };