/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Course = { 'bba' : null } |
  { 'bca' : null } |
  { 'bsc' : null } |
  { 'llb' : null } |
  { 'mba' : null } |
  { 'other' : null } |
  { 'bcom' : null } |
  { 'pharmacy' : null } |
  { 'btech' : null } |
  { 'agriculture' : null } |
  { 'diploma' : null };
export type EntranceExam = { 'jee' : null } |
  { 'cuet' : null } |
  { 'neet' : null } |
  { 'none' : null };
export interface Lead {
  'twelfthStream' : Stream,
  'otherCourseText' : [] | [string],
  'interestedCourse' : Course,
  'fullName' : string,
  'mobileNumber' : string,
  'district' : string,
  'needsDrccSupport' : boolean,
  'twelfthPercentage' : bigint,
  'entranceExam' : EntranceExam,
}
export type Stream = { 'arts' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export interface _SERVICE {
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'submitLead' : ActorMethod<
    [
      string,
      string,
      string,
      Stream,
      bigint,
      Course,
      [] | [string],
      boolean,
      EntranceExam,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];