/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    twelfthStream: Stream;
    interestedCourse: Course;
    fullName: string;
    mobileNumber: string;
    district: string;
    needsDrccSupport: boolean;
    twelfthPercentage: bigint;
    entranceExam: EntranceExam;
}
export enum Course {
    bba = "bba",
    bca = "bca",
    bsc = "bsc",
    other = "other",
    bcom = "bcom",
    diploma = "diploma"
}
export enum EntranceExam {
    jee = "jee",
    cuet = "cuet",
    neet = "neet",
    none = "none"
}
export enum Stream {
    arts = "arts",
    commerce = "commerce",
    science = "science"
}
export interface backendInterface {
    getAllLeads(): Promise<Array<Lead>>;
    submitLead(fullName: string, mobileNumber: string, district: string, twelfthStream: Stream, twelfthPercentage: bigint, interestedCourse: Course, needsDrccSupport: boolean, entranceExam: EntranceExam): Promise<void>;
}
import type { Course as _Course, EntranceExam as _EntranceExam, Lead as _Lead, Stream as _Stream } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLead(arg0: string, arg1: string, arg2: string, arg3: Stream, arg4: bigint, arg5: Course, arg6: boolean, arg7: EntranceExam): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(arg0, arg1, arg2, to_candid_Stream_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Course_n12(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_EntranceExam_n14(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(arg0, arg1, arg2, to_candid_Stream_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Course_n12(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_EntranceExam_n14(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_Course_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EntranceExam_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntranceExam): EntranceExam {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Stream_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stream): Stream {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twelfthStream: _Stream;
    interestedCourse: _Course;
    fullName: string;
    mobileNumber: string;
    district: string;
    needsDrccSupport: boolean;
    twelfthPercentage: bigint;
    entranceExam: _EntranceExam;
}): {
    twelfthStream: Stream;
    interestedCourse: Course;
    fullName: string;
    mobileNumber: string;
    district: string;
    needsDrccSupport: boolean;
    twelfthPercentage: bigint;
    entranceExam: EntranceExam;
} {
    return {
        twelfthStream: from_candid_Stream_n4(_uploadFile, _downloadFile, value.twelfthStream),
        interestedCourse: from_candid_Course_n6(_uploadFile, _downloadFile, value.interestedCourse),
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        district: value.district,
        needsDrccSupport: value.needsDrccSupport,
        twelfthPercentage: value.twelfthPercentage,
        entranceExam: from_candid_EntranceExam_n8(_uploadFile, _downloadFile, value.entranceExam)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
}): Stream {
    return "arts" in value ? Stream.arts : "commerce" in value ? Stream.commerce : "science" in value ? Stream.science : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bba: null;
} | {
    bca: null;
} | {
    bsc: null;
} | {
    other: null;
} | {
    bcom: null;
} | {
    diploma: null;
}): Course {
    return "bba" in value ? Course.bba : "bca" in value ? Course.bca : "bsc" in value ? Course.bsc : "other" in value ? Course.other : "bcom" in value ? Course.bcom : "diploma" in value ? Course.diploma : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jee: null;
} | {
    cuet: null;
} | {
    neet: null;
} | {
    none: null;
}): EntranceExam {
    return "jee" in value ? EntranceExam.jee : "cuet" in value ? EntranceExam.cuet : "neet" in value ? EntranceExam.neet : "none" in value ? EntranceExam.none : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Course_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Course): _Course {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_EntranceExam_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntranceExam): _EntranceExam {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Stream_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): _Stream {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
} {
    return value == Stream.arts ? {
        arts: null
    } : value == Stream.commerce ? {
        commerce: null
    } : value == Stream.science ? {
        science: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Course): {
    bba: null;
} | {
    bca: null;
} | {
    bsc: null;
} | {
    other: null;
} | {
    bcom: null;
} | {
    diploma: null;
} {
    return value == Course.bba ? {
        bba: null
    } : value == Course.bca ? {
        bca: null
    } : value == Course.bsc ? {
        bsc: null
    } : value == Course.other ? {
        other: null
    } : value == Course.bcom ? {
        bcom: null
    } : value == Course.diploma ? {
        diploma: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntranceExam): {
    jee: null;
} | {
    cuet: null;
} | {
    neet: null;
} | {
    none: null;
} {
    return value == EntranceExam.jee ? {
        jee: null
    } : value == EntranceExam.cuet ? {
        cuet: null
    } : value == EntranceExam.neet ? {
        neet: null
    } : value == EntranceExam.none ? {
        none: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
